on:
  workflow_dispatch:
    inputs:
      bench_count:
        type: number
        description: "Number of times to run the benchmark"
        default: 30
name: benchmark
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go_test.sum
      - name: Run tests for benchmark
        run: make bench
        env:
          BENCH_COUNT: ${{ inputs.bench_count }}
